### ISSUE TITLE
Change Todo section colors in dark mode

### ISSUE THREAD

**Issue by nicosh** [nicosh/chrome-dev-newtab#19]
While in dark mode the Todo cards colors should be changed to match the dark theme.

**Comment by kashish-d** [comment]
Can i work on this one?

**Comment by nicosh** [comment]
@kashish-d sure!

**Comment by kashish-d** [comment]
Great! I will start working on it

**Comment by everly-gif** [comment]
hey I would like to give this a try! could I work on this ? Do assign it to me @nicosh

**Comment by AmreshSinha** [comment]
Can I try it? :)
Also, suggest some good color palettes from colorhunt website. :blush:

**Comment by nicosh** [comment]
@AmreshSinha  sure!

**Comment by AmreshSinha** [comment]
I was about to make a PR but saw that you have already did changes :thinking: :disappointed:

**Comment by nicosh** [comment]
@AmreshSinha i didn't made any changes to todo section
