### ISSUE TITLE
Used cpu  is (probably) showing wrong percentage

### ISSUE THREAD

**Issue by nicosh** [nicosh/chrome-dev-newtab#2]
The % of CPU used  is never changing and is probably different from the real one.

**To reproduce** 
Open your system task manager, the % of used CPU will be different from the one showed in the top right corner of the plugin.  

[Relevant code](https://github.com/nicosh/chrome-dev-newtab/blob/main/src/components/infobar/stats.js#L20)
[Docs](https://developer.chrome.com/docs/extensions/reference/system_cpu/)

**Comment by srijit2002** [comment]
@nicosh I think we need to run it at some intervals to get the correct data
check [this](https://stackoverflow.com/questions/24473134/chrome-system-cpu-api-usage)

**Comment by nicosh** [comment]
@srijit2002 it's already inside an interval
https://github.com/nicosh/chrome-dev-newtab/blob/8faf54b17a1f526c5f88acae6f38b03ff00be6d2/src/components/infobar/stats.js#L32
