### ISSUE TITLE
use chrome.storage instead that  localStorage

### ISSUE THREAD

**Issue by nicosh** [nicosh/chrome-dev-newtab#3]
Use [chrome apis](https://developer.chrome.com/docs/extensions/reference/storage/) `chrome.storage` for storage purposes instead that `localStorage` everywhere is needed.

Ex :
https://github.com/nicosh/chrome-dev-newtab/blob/486de7828d71e0010f622d0a5810605afc68d604/src/components/todo/index.js#L31
https://github.com/nicosh/chrome-dev-newtab/blob/486de7828d71e0010f622d0a5810605afc68d604/src/components/context/appContext.js#L7
https://github.com/nicosh/chrome-dev-newtab/blob/486de7828d71e0010f622d0a5810605afc68d604/src/components/context/appContext.js#L25
https://github.com/nicosh/chrome-dev-newtab/blob/486de7828d71e0010f622d0a5810605afc68d604/src/components/todo/index.js#L37
https://github.com/nicosh/chrome-dev-newtab/blob/486de7828d71e0010f622d0a5810605afc68d604/src/components/misc/github/index.js#L6-L7
https://github.com/nicosh/chrome-dev-newtab/blob/486de7828d71e0010f622d0a5810605afc68d604/src/components/misc/github/index.js#L52-L74
https://github.com/nicosh/chrome-dev-newtab/blob/486de7828d71e0010f622d0a5810605afc68d604/src/components/editor.js#L9-L20

**Comment by Croustys** [comment]
I’d be happy to look into that issue and fix it in the upcoming day(s).

**Comment by nicosh** [comment]
@Croustys thanks! Assigned!
 [CONTRIBUTING.md](https://github.com/nicosh/chrome-dev-newtab/blob/main/CONTRIBUTING.md)

**Comment by Croustys** [comment]
submitted a pr! <3 #17
